### ISSUE TITLE
New refresh rate is not shown in SteamOS 3.5's unified frame limit management slider

### ISSUE THREAD

**Issue by veryrealwildcat** [ryanrudolfoba/SteamDeck-RefreshRateUnlocker#10]
if you opt into the preview update channels you'll see that the refresh rate and fps sliders got merged into one which makes it a tonne better, but it only shows up 60 fps/hz instead of 70. While a workaround is to enable the old 2 sliders in settings -> display advanced, the script should just be updated. 

new slider:
![steamuserimages-a akamaihd2](https://github.com/ryanrudolfoba/SteamDeck-RefreshRateUnlocker/assets/73769956/29ac1573-d73b-40b7-9c23-b63448c15a96)
old sliders:
![steamuserimages-a akamaihd](https://github.com/ryanrudolfoba/SteamDeck-RefreshRateUnlocker/assets/73769956/ee142ff7-f945-4d87-88d5-c9f1d333de58)

**Comment by snormonster** [comment]
Interestingly enough, I am also on the preview update and while I do not have the new OLED SD with the latest update my slider goes all the way up to 90Hz so I can now choose 70Hz for my screen without the need for external scripts.

**Comment by ryanrudolfoba** [comment]
> Interestingly enough, I am also on the preview update and while I do not have the new OLED SD with the latest update my slider goes all the way up to 90Hz so I can now choose 70Hz for my screen without the need for external scripts.

That is true and the limit is from 45-90. Its wide open outside the ranges of LCD and kinda dangerous when you inadvertently set the refresh above 70. 
I want to make an update on this script once i have my hands on the OLED. Ideally this is what i want the script to behave -

1. Perform sanity check if OLED / LCD.
2. If OLED no further action needed exit immediately.
3. If LCD change the limit to 30-70.

**Comment by ryanrudolfoba** [comment]
Just updated to 3.5.3 and refresh rate is back to 40-60.

**Comment by RedSoul001** [comment]
Steam OS 3.5.5 was released to the Stable channel a few hours ago which is unfortunate because I just found out about this project today and installed it immediately to get 30hz to 40hz referesh rate support. Now it no longer works. I tested setting it up with this new update and as expected nothing happened. Looking forward to any future updates.

**Comment by ryanrudolfoba** [comment]
Go to Settings > Developer Options
Disable the Unified Frame Limit Management

Reboot and you will get the unlocked refresh rates back 20-70Hz.

**Comment by 1basti1** [comment]
> > Interestingly enough, I am also on the preview update and while I do not have the new OLED SD with the latest update my slider goes all the way up to 90Hz so I can now choose 70Hz for my screen without the need for external scripts.
> 
> That is true and the limit is from 45-90. Its wide open outside the ranges of LCD and kinda dangerous when you inadvertently set the refresh above 70. I want to make an update on this script once i have my hands on the OLED. Ideally this is what i want the script to behave -
> 
> 1. Perform sanity check if OLED / LCD.
> 2. If OLED no further action needed exit immediately.
> 3. If LCD change the limit to 30-70.

OLED goes down to 45Hz?
I actually would love to see it go lower than that. Because half refresh gives input lag. I'm really worried setting the OLED to 40fps has huge input lag..

**Comment by martindmtrv** [comment]
On latest stable SteamOS 3.5.5 LCD steam deck seems that they have removed the option to disable unified frame limit management

I don't see it under display nor dev options

**Comment by martindmtrv** [comment]
Actually after a reboot it now shows up under settings > display > advanced the option is there

**Comment by PS2ClassicsVault** [comment]
Same.issuenherenand im on stabls

**Comment by LhymeFruit** [comment]
> if you opt into the preview update channels you'll see that the refresh rate and fps sliders got merged into one which makes it a tonne better, but it only shows up 60 fps/hz instead of 70. While a workaround is to enable the old 2 sliders in settings -> display advanced, the script should just be updated.
> 
> new slider: ![steamuserimages-a akamaihd2](https://private-user-images.githubusercontent.com/73769956/282279878-29ac1573-d73b-40b7-9c23-b63448c15a96.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzODQ3MzAsIm5iZiI6MTcwMTM4NDQzMCwicGF0aCI6Ii83Mzc2OTk1Ni8yODIyNzk4NzgtMjlhYzE1NzMtZDczYi00MGI3LTljMjMtYjYzNDQ4YzE1YTk2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDIyNDcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MDI5ZjY0MDBiMTcwNGQwYzQwMDFmY2U1MjJmZmJmYzRkMjcwMGNhNzcyNjc3ZTJhNmNjNmMyYTNiZGY0NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lpapa8CeaIwpiDtXjcV7inGOob3cfEOnJH0Y3MzwDHA) old sliders: ![steamuserimages-a akamaihd](https://private-user-images.githubusercontent.com/73769956/282279880-ee142ff7-f945-4d87-88d5-c9f1d333de58.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzODQ3MzAsIm5iZiI6MTcwMTM4NDQzMCwicGF0aCI6Ii83Mzc2OTk1Ni8yODIyNzk4ODAtZWUxNDJmZjctZjk0NS00ZDg3LTg4ZDUtYzlmMWQzMzNkZTU4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDIyNDcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwODQyNTEyZjA4ZGJhMTY5NTI2OWUyYzBhMGVlYzJmMDk0NDIxNDYzNDZlYmI1NmU2NjBiOTBkMjhiMDY4YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LN2B4hRoaVpjLq4G1VeI1JrWfeKrkDwc7UM1T36cZDA)

Thanks for showing how to fix it, I thought it was worked in the new update and I had no idea about that display setting.

**Comment by DreamboxMinerva** [comment]
With the latest update (the one that adds recording feature) they've now completely removed the option to revert to the old theme, it force the unified style, what a bummer.

So the mod is now basically unusable..

**Comment by jrouzies-fr** [comment]
> With the latest update (the one that adds recording feature) they've now completely removed the option to revert to the old theme, it force the unified style, what a bummer.
> 
> So the mod is now basically unusable..

Sad, I was about to ask, how can I set my Hz to 30, to have proper frame pacing for 30 FPS games, even on OLED Screen

**Comment by linyihai** [comment]
> With the latest update (the one that adds recording feature) they've now completely removed the option to revert to the old theme, it force the unified style, what a bummer.
> 
> So the mod is now basically unusable..

This is Why I downgrade to 3.5.x stable , but tody the stable channel had update to 3.6.x, so this mod won't take affect anymore. 

To be honest, really need 35/70hz setting for some game due to the poor steam deck performance.  Anyone can stand up to fix this or guide us to workaround it?

**Comment by snormonster** [comment]
I haven't been using my Steam Deck much lately, but I am hesitant now to update, because I can still use 35 fps / 70 Hz in games.

I am really hoping for a fix for this, too.

**Comment by enamul6m** [comment]
Just now updated to 3.6.19 and there is no option for unified frame limit management. Please find a fix.

**Comment by lostgoat** [comment]
Gamescope supports config files now, which allow for overriding default display parameters.

**Comment by ryanrudolfoba** [comment]
> Gamescope supports config files now, which allow for overriding default display parameters.
> 
> This should allow overclocking the display without removing the read only lock and it allows the change to be preserved across OS updates.

Do you have a link for this i can read on? The one that shows up for me is gamescope plus from ChimeraOS.

I've started patching gamescope to override the default values. Here it shows my OLED can go upto 100Hz -

![PXL_20241106_214135481 MP](https://github.com/user-attachments/assets/85b7adb9-caf8-44d3-8197-d89bc55c3179)


But if config file is an option that will be better and easier.

**Comment by lostgoat** [comment]
Some details here:

https://github.com/ValveSoftware/gamescope/tree/master/scripts

**Comment by lostgoat** [comment]
In particular, this is the config file you’d want to override:

https://github.com/ValveSoftware/gamescope/blob/7dd1bcd9102a17e039970ccd9a324a9fe8365d6d/scripts/00-gamescope/displays/valve.steamdeck.lcd.lua#L17

**Comment by ryanrudolfoba** [comment]
wow that's awesome and way easier than patching and building gamescope from source! Thanks for those links i have an idea how to proceed now

**Comment by Koanrade** [comment]
I've made new valve.steamdeck.lcd.lua file at ~/.config/gamescope/ with less dynamic refresh rates including 30hz but nothing seems to have changed. SD UI still allows for changes in refresh rates even to those not specified in .lua file and the lower limit stays at 40hz.
Also, where does exactly modegen get 'refresh' variable from? example 'gamescope.modegen.calc_max_clock(mode, refresh)'.
Found some leads at https://github.com/ValveSoftware/gamescope/blob/master/src/steamcompmgr.cpp#L2500

**Comment by ryanrudolfoba** [comment]
And this one is worrisome for me -

`Gamescope scripting/configuration is currently experimental and subject to change massively.

Scripts and configs working between revisions is not guaranteed to work, it should at least not crash... probably.`

Looking forward if there is a new SteamOS update and it is not compatible with the modified config then the risk of crashing not able to get to Game Mode will be an issue.

But if we use a patched gamescope (built from source with new values), a SteamOS update will be safe as it will be overridden and no remnant of incompatible config.

With that I'm leaning towards a modified / patched gamescope instead of config files.

**Comment by Baz4r4** [comment]
Will it be possible to set 35fps and 70hz?

**Comment by ginpigin** [comment]
> i haven't tried using the config file. What im using is the longer method - building gamescope from source with new values for the refresh rate limit. That one is a success for me - ![PXL_20241107_153914955 MP](https://private-user-images.githubusercontent.com/98122529/384524036-1b11b516-7dd1-4247-be1e-830ddbd1d972.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMzMxNjMsIm5iZiI6MTczMTMzMjg2MywicGF0aCI6Ii85ODEyMjUyOS8zODQ1MjQwMzYtMWIxMWI1MTYtN2RkMS00MjQ3LWJlMWUtODMwZGRiZDFkOTcyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDEzNDc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyOTllZTYzODc0NjFmM2M2MmE2YTY0NjU1NzdmZDE1MGYwZGRkNjJkZWYwNTk2MDAyYzU2ZTYyMWIzOTljOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hghFWlyyyk8etB9FbnFFktCV_Zocy_G1-b4UTJ9hiKk)
> 
> I'll tinker around later with the config file as that one is more promising and more easier

How can a regular user do this?

**Comment by ryanrudolfoba** [comment]
script has been updated to support SteamOS 3.6.20.

**Comment by ryanrudolfoba** [comment]
> I've made new valve.steamdeck.lcd.lua file at ~/.config/gamescope/ with less dynamic refresh rates including 30hz but nothing seems to have changed. SD UI still allows for changes in refresh rates even to those not specified in .lua file and the lower limit stays at 40hz. Also, where does exactly modegen get 'refresh' variable from? example 'gamescope.modegen.calc_max_clock(mode, refresh)'. Found some leads at https://github.com/ValveSoftware/gamescope/blob/master/src/steamcompmgr.cpp#L2500

the lua config file only seems to work on the Preview SteamOS 3.7.x

**Comment by iOS4all** [comment]
Please is there any update for Oled model?
We really need 30hz
