### ISSUE TITLE
framerate goes back to 60 when using ui elements

### ISSUE THREAD

**Issue by LhymeFruit** [ryanrudolfoba/SteamDeck-RefreshRateUnlocker#13]
I've noticed it on 

Main menu
Volume change,
Controller settings,
Pretty much anything that tabs out from a game,
(Not including side menus)

**Comment by ryanrudolfoba** [comment]
Thats normal behavior as the "HOME SCREEN" is locked to 60. Only when playing games the refresh rate goes higher/ lower.
