### ISSUE TITLE
Steam Deck OLED Support

### ISSUE THREAD

**Issue by CreeperofDoom** [ryanrudolfoba/SteamDeck-RefreshRateUnlocker#14]
I really want 30hz and 40hz Back onto my Steam Deck with the OLED Model. The Steam Deck update that added recording altered the Frame / Refresh Rate limiter so this mod may need an update to get working again. The Steam Deck OLED has 120hz mods for some reason but my model doesn’t support that and i am sure that one doesn’t allow me to go to 30hz

**Comment by ryanrudolfoba** [comment]
This is being discussed here -

https://github.com/ryanrudolfoba/SteamDeck-RefreshRateUnlocker/issues/10
