### ISSUE TITLE
Hash mismatch - possible corrupt download. Clone the repo again! Error.

### ISSUE THREAD

**Issue by totallynotbakadestroyer** [ryanrudolfoba/SteamDeck-RefreshRateUnlocker#16]
Hello!
New version is always ending up with "Hash mismatch - possible corrupt download. Clone the repo again!" due to missing files in your repo.
Basically, the whole "gamescope" with original and unlocked versions is just missing. Can you please add it?

Thank you very much for your work!

**Comment by DigitalFriends** [comment]
Same issue here

**Comment by Baz4r4** [comment]
Same

**Comment by Hollyrious** [comment]
Same here.

**Comment by Djig94** [comment]
Тоже самое

**Comment by Djig94** [comment]
Same here

**Comment by Djig94** [comment]
Same here...

**Comment by sergeivgr** [comment]
Same here.

**Comment by ryanrudolfoba** [comment]
script has been updated to support SteamOS 3.6.20.
