### ISSUE TITLE
Restore sub-35hz support

### ISSUE THREAD

**Issue by desertprinter** [ryanrudolfoba/SteamDeck-RefreshRateUnlocker#17]
There is no option for 30hz or even 20hz now, the lowest now is 35hz, which isn’t even well suited for a 30fps cap. Why was there a regression here? Seriously, why?

**Comment by desertprinter** [comment]
If this sound quite I’m annoyed, that’s because I am, because I don’t get the regression here.

**Comment by desertprinter** [comment]
![IMG_2001](https://github.com/user-attachments/assets/48d7cae4-c9e2-4bd7-a645-03750946a46c)
Part of my confusion is that I can’t understand why there was a regression here, especially because you can clearly still underclock the display (given the normal limit is 40hz) so to give no option out of the box for 20hz is just confusing to me.

**Comment by Baz4r4** [comment]
May i ask why would you want 30hz? 30fps runs well with 60hz

**Comment by desertprinter** [comment]
> May i ask why would you want 30hz? 30fps runs well with 60hz

I would have wanted it, because the Deck is wasting 30hz when doing 30fps on 60hz, and thus battery life issues, but it turns out this is a causality of Valve now forcing the unified slider.
