### ISSUE TITLE
Insecure storage of user password.

### ISSUE THREAD

**Issue by eth-p** [ryanrudolfoba/SteamDeck-RefreshRateUnlocker#2]
Hi there! I was reading through the install script trying to understand how persistence through updates is achieved, and I noticed this line where the installer creates a helper script that saves the `sudo` password into a plain text file.

https://github.com/ryanrudolfoba/SteamDeck-RefreshRateUnlocker/blob/main/install-RefreshRateUnlocker.sh#L119

It's a tenacious way to achieve superuser persistence, but there's a couple problems:

1. It will break whenever the password is changed; and
2. It's against security best practices.

The idiomatic way of running something as root on startup would be to create a `systemd` service that runs as root. That's also a bit difficult to do securely, though, and could lead to local privilege escalation if you have it point to a directory that can be moved or written to by the user.

If you wanted to use a systemd service, I would recommend writing the root-executed helper scripts to somewhere under `/etc`, where the user can't move them or replace them.

Also, if you don't have experience with creating systemd services, I would highly recommend [this article](https://www.digitalocean.com/community/tutorials/understanding-systemd-units-and-unit-files) by Digital Ocean. It's helped me on multiple occasions :)

**Comment by ryanrudolfoba** [comment]
Thank you for providing feedback i appreciate it. I've rewritten the script to use systemd and added a quick checker to verify if the service is running or not.

**Comment by ryanrudolfoba** [comment]
I'll be closing this as the concern has been addressed.

**Comment by eth-p** [comment]
Hi there! I just gave the changes a read through, and it's a great improvement!

Unfortunately, though, the systemd service that gets installed can be leveraged for local privilege escalation from the `deck` user to `root` user. If you replace the post-install script under `~/1RefreshRateUnlocker` with anything else, systemd will run it as uid 0 upon next boot.

Pointing a system-level systemd service to an executable located under a user-controlled path is extremely difficult to do securely, even if you `chown` and `chmod` the `1RefreshRateUnlocker` directory. I would highly recommend converting the script to `bash -c '...'` and use that as the `Exec` option instead, or if that's not an option, placing it under `/etc` somewhere.

**Comment by ryanrudolfoba** [comment]
Are you tefer

![Screenshot_20230409-075719](https://user-images.githubusercontent.com/98122529/230771133-c82e7534-6fdd-4f8f-b9e2-b263b3f60c46.png)

**Comment by ryanrudolfoba** [comment]
Are you referring to this? The exec is using bash -c already -

![Screenshot_20230409-075719](https://user-images.githubusercontent.com/98122529/230771185-76e43f51-4d8d-4be2-bd4a-83d4b09f1cca.png)

**Comment by eth-p** [comment]
Yep, that's the part of the unit file.

https://github.com/ryanrudolfoba/SteamDeck-RefreshRateUnlocker/blob/main/install-RefreshRateUnlocker.sh#L161

```
[Service] 
 Type=oneshot 
 RemainAfterExit=yes 
 ExecStart=/bin/bash -c '/home/deck/1RefreshRateUnlocker/post-install-RefreshRateUnlocker.sh'
```

My bad on not explaining myself very well, but what I meant was taking the contents of `post-install-RefreshRateUnlocker.sh` and converting it into `bash -c 'foo; bar; baz'`. That single command would then go under the service's `Exec=`, keeping it self-contained.

**Comment by ryanrudolfoba** [comment]
Got it. I'll give it a try.
