### ISSUE TITLE
Doesn't work with sudo password with whitespace in it

### ISSUE THREAD

**Issue by Zebrazilla** [ryanrudolfoba/SteamDeck-RefreshRateUnlocker#5]
Had to change sudo password to run this as the one I had contained a whitespace, which caused a failure when the script checked that the sudo password was correct. A minor nuisance since all I had to do was change the password, but still an issue.

**Comment by Zebrazilla** [comment]
An update to this: I've rebooted several times with the new password, still the same issue. I've also tried doing 'sudo steamos-readonly disable', checking status with 'sudo steamos-readonly status', and setting back. I've tried changing passwords again to something different, simple ones with just a letter or two, or a few letters and numbers. Still the same issue.

I don't know how this connects to the initial password not working. That first password had a whitespace at the end of it. It might've been this issue all along, whatever this issue is. Quite strange.

I could go about doing the changes manually, but I really want the service and the QOL that brings.

**Comment by ryanrudolfoba** [comment]
can u share the steps how u are to replicate it?

**Comment by Zebrazilla** [comment]
> can u share the steps how u are to replicate it?

Just following the process as laid out in the installation steps:

1. opening konsole
2. cloning the repo
3. chmod for execute on the install script
4. running the script
5. entering the password
6. choosing refresh rate setting

It succesfully creates the files in /home/deck, but anything needing sudo fails, despite the script having checked and verified that the password is correct.

I just attempted to manually run one of the early commands in the script requiring sudo access which should just work, but the result is bewildering to me:
![Screenshot_20230621_230011](https://github.com/ryanrudolfoba/SteamDeck-RefreshRateUnlocker/assets/6796156/a73538c9-ba6c-4acc-9b6c-b67365ba4bd1)
The password is correct, otherwise it would have said so, but it seems I'm still not being granted proper sudo access. Very strange.

Regarding sudo, my deck is stock besides having installed Decky Loader, which also needed sudo access. While that was a while back now, it worked at the time, and I haven't touched the desktop system since really.

Whatever the issue is, it's clearly not related to the script at least. Why I'm not getting proper sudo access is beyond me atm. though..

**Comment by Zebrazilla** [comment]
> can u share the steps how u are to replicate it?

Just following the process as laid out in the installation steps:

1. opening konsole
2. cloning the repo
3. chmod for execute on the install script
4. running the script
5. entering the password
6. choosing refresh rate setting

It succesfully creates the files in /home/deck, but anything needing sudo fails, despite the script having checked and verified that the password is correct.

I just attempted to manually run one of the early commands in the script requiring sudo access which should just work, but the result is bewildering to me:
![Screenshot_20230621_231558](https://github.com/ryanrudolfoba/SteamDeck-RefreshRateUnlocker/assets/6796156/ef0b82cd-100c-4f9a-978b-6fc118324df9)

The password is correct, otherwise it would have said so, but it seems I'm still not being granted proper sudo access. Very strange.

Regarding sudo, my deck is stock besides having installed Decky Loader, which also needed sudo access. While that was a while back now, it worked at the time, and I haven't touched the desktop system since really.

Whatever the issue is, it's clearly not related to the script at least. Why I'm not getting proper sudo access is beyond me atm. though..

**Comment by Zebrazilla** [comment]
I finally found the culprit to be Tailscale.

I had to issue the command `sudo systemd-sysext unmerge` in order to temporarily disable it (re-enabling it later with `sudo systemd-sysext merge`), which allowed changes to the filesystem at `/bin/`, and as such the script now works. I've verified and 70 hz now works like a charm.

Thank you for the script, this feels amazing for my eyeballs and braincells!

In case anyone else stumbles upon this issue, it may also be applicable to TunnelDeck (OpenVPN) if installed via Decky Loader. See [this issue](https://github.com/steve228uk/TunnelDeck/issues/2) on their repo.

**Comment by Zebrazilla** [comment]
Still curious why the initial issue was that my original password didn't work, I went changed it back and re-ran the script, and ran into the original issue of the script not being able to verify it.

To be clear, my original password ended with a whitespace. I tried changing password to one with a whitespace in the middle somewhere, and that worked fine. So it may very well be that the script can't handle passwords with whitespaces at the end.

If you can double-check that, with a password with whitespace at the end, it may help others who also are mad enough to have whitespaces at the end of their passwords 😅

**Comment by ryanrudolfoba** [comment]
no worries. Im able to replicate the whitespace issue in password. It only happens if the whitespace is at the end of the line.

quick fix is to add IFS=
