### ISSUE TITLE
changing settings does not update the script

### ISSUE THREAD

**Issue by xamindar** [ryanrudolfoba/SteamDeck-RefreshRateUnlocker#6]
If you change to a different setting (without uninstalling and starting all over), this script is not updated to reflect the change:
/etc/systemd/system/RefreshRateUnlocker.sh

This is fine I guess until the next steamos update that resets the /bin/gamescope-session file back to default, in which case the sed command in the above script will change it to the first setting you tried, not the one you settled on.

Also, the script will run on every reboot and "try" to patch the setting.

**Comment by ryanrudolfoba** [comment]
sorry for late reply. script has been updated to latest stable SteamOS 3.6.20.
