### ISSUE TITLE
35hz option?

### ISSUE THREAD

**Issue by avxkim** [ryanrudolfoba/SteamDeck-RefreshRateUnlocker#8]
Hello, is it possible to add 35hz option? I want to lock my FPS to 35 and set 35hz

**Comment by ryanrudolfoba** [comment]
Yes it is implemented.

![247296032-06b7b897-d349-4bfa-8671-c1bc8a3b0120](https://github.com/ryanrudolfoba/SteamDeck-RefreshRateUnlocker/assets/98122529/2e1ac7a2-3908-4489-ae05-683273031c00)

**Comment by avxkim** [comment]
@ryanrudolfoba will 40,70 allow me to choose 35hz/35fps?

**Comment by ryanrudolfoba** [comment]
You have to choose either one of the following -

30,60
30,70
20,60
20,70

Then adjust the slider until it reaches 35Hz

**Comment by avxkim** [comment]
@ryanrudolfoba have you tried 35FPS/35HZ? how it does feel?

**Comment by ryanrudolfoba** [comment]
35Hz / 35FPS it works good for games that have difficulties on 40FPS but its goes good for 35FPS. example for this will be games like Elden Ring, Cyberpunk.

but not all panels are created equal. your panel might have a noticeable flicker when it goes below 40Hz. When that happens you can gradually overclock the panel upto 70Hz then set the FPS cap to 35FPS.

**Comment by ryanrudolfoba** [comment]
Haven't heard back if need further help feel free to re-open this issue.
