### ISSUE TITLE
New SteamOS update merged framerate and refresh rate sliders and broke the patch.

### ISSUE THREAD

**Issue by Butterscotch96** [ryanrudolfoba/SteamDeck-RefreshRateUnlocker#9]
[https://www.reddit.com/r/SteamDeck/s/R5uLFxEmXi](https://www.reddit.com/r/SteamDeck/s/R5uLFxEmXi)

**Comment by ryanrudolfoba** [comment]
I'm on SteamOS3.5.1 too and this is steps i do to re-activate the patch -

Go to Settings > Developer Options
Disable the Unified Frame Limit Management

Reboot and you will get the unlocked refresh rates back 20-70Hz.
